# Generated by Django 5.2.9 on 2025-12-29 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("infrastructure", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productomodel",
            name="empresa",
        ),
        migrations.DeleteModel(
            name="EmpresaModel",
        ),
        migrations.DeleteModel(
            name="ProductoModel",
        ),
    ]
