# Generated by Django 5.2.9 on 2025-12-29 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "nit",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("direccion", models.TextField()),
                ("telefono", models.CharField(max_length=20)),
            ],
            options={
                "verbose_name": "Empresa",
                "verbose_name_plural": "Empresas",
                "db_table": "empresa",
            },
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "codigo",
                    models.CharField(
                        max_length=50, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("caracteristicas", models.TextField()),
                ("precios", models.JSONField()),
                (
                    "empresa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="productos",
                        to="shared_domain.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Producto",
                "verbose_name_plural": "Productos",
                "db_table": "producto",
            },
        ),
    ]
